BUDGET_CATEGORIES = [
    ("98 Degrees Trip", "Trips with Friends", "Vacations & Special Experiences", True, False),
    ("Administrative Fees", "Utilities", "House, Cars, & Insurance", False, True),
    ("Airfare", "Family Vacations", "Vacations & Special Experiences", True, False),
    ("Airport Food/Costs", "Family Vacations", "Vacations & Special Experiences", True, False),
    ("Amazon", "General Shopping", "Shopping", False, True),
    ("Amazon Returns", "General Shopping", "Shopping", True, True),
    ("ATM Deposit", "Financial Transfers", "Financial Transactions", False, True),
    ("Baby Supplies", "Kid's Essentials", "Taking Care of the Kids", False, True),
    ("Bags & Luggage", "General Shopping", "Shopping", True, True),
    ("Benson Boone Concert", "Trips with Friends", "Vacations & Special Experiences", True, False),
    ("Books", "Activities for the Kids", "Routine Entertainment", True, True),
    ("Bottlerock", "Trips with Friends", "Vacations & Special Experiences", True, False),
    ("Bunnies", "Pets", "Kid's Enrichment", False, True),
    ("Cammi's Birthday Trip", "Trips with Friends", "Vacations & Special Experiences", True, False),
    ("Camp Flog Gnaw", "Trips with Friends", "Vacations & Special Experiences", True, False),
    ("Car Insurance", "Cars & Transportation", "House, Cars, & Insurance", False, True),
    ("Car Maintenance", "Cars & Transportation", "House, Cars, & Insurance", False, True),
    ("Car Wash", "Cars & Transportation", "House, Cars, & Insurance", True, True),
    ("Charging/Gas", "Cars & Transportation", "House, Cars, & Insurance", False, True),
    ("Childcare/Tuition", "Childcare/Tutoring", "Taking Care of the Kids", False, True),
    ("Cleaning Services", "House Maintenance", "House, Cars, & Insurance", True, True),
    ("Clothes", "Aesthetics", "Vanity & Pleasure", True, True),
    ("Coachella", "Dates as a Couple", "Vacations & Special Experiences", True, False),
    ("Cosmetics", "Aesthetics", "Vanity & Pleasure", True, True),
    ("Country Music Festival", "Trips with Friends", "Vacations & Special Experiences", True, False),
    ("Credit Card Fees", "Financial Fees", "Financial Transactions", False, True),
    ("Credit Card Rewards", "Financial Earnings", "Financial Transactions", False, True),
    ("Date Nights", "Dates as a Couple", "Vacations & Special Experiences", True, True),
    ("David's Payroll", "Career Income", "Income", False, True),
    ("Dentistry", "Health", "Health & Fitness", False, True),
    ("Digital Storage", "Utilities", "House, Cars, & Insurance", False, True),
    ("Disney Cruises", "Family Vacations", "Vacations & Special Experiences", True, False),
    ("Disney Half-Marathon", "Fitness", "Health & Fitness", True, False),
    ("Disney On Ice", "Activities for the Kids", "Vacations & Special Experiences", True, False),
    ("Disney Vacation Club", "Family Vacations", "Vacations & Special Experiences", True, True),
    ("Disneyland", "Family Vacations", "Vacations & Special Experiences", True, False),
    ("Donations to Causes", "Donations", "Donations & Giving", True, True),
    ("Drinking & Bars", "Altered States", "Vanity & Pleasure", True, True),
    ("Earned Interest", "Financial Earnings", "Income", False, True),
    ("Educational Apps", "Activities for the Kids", "Kid's Enrichment", True, True),
    ("Extracurricular Classes", "Activities for the Kids", "Kid's Enrichment", True, True),
    ("Family Loan", "Giving", "Donations & Giving", True, False),
    ("Fast Food", "Eating Out", "Food", True, True),
    ("Field Trip", "Activities for the Kids", "Kid's Enrichment", False, True),
    ("Fitness Bet", "Fitness", "Health & Fitness", True, True),
    ("Fitness Tech", "Fitness", "Health & Fitness", True, True),
    ("Furniture", "Decor & Furniture", "House, Cars, & Insurance", True, False),
    ("Gambling Bet", "Gambling", "Routine Entertainment", True, True),
    ("Gambling Earnings", "Gambling", "Routine Entertainment", True, True),
    ("General Airfare", "General Airfare", "Vacations & Special Experiences", True, True),
    ("Gifts", "Giving", "Donations & Giving", False, True),
    ("Girl's Trip", "Trips with Friends", "Vacations & Special Experiences", True, False),
    ("Groceries", "Food for Home", "Food", False, True),
    ("Gym Equipment", "Fitness", "Health & Fitness", True, False),
    ("Hawaii Vacation", "Family Vacations", "Vacations & Special Experiences", True, False),
    ("Home Decor", "Furniture & Decor", "Shopping", True, True),
    ("Hotels for Verily", "David's Career Expenses", "Career Expenses", False, True),
    ("HSA Reimbursement", "General Income", "Income", False, True),
    ("HVAC Systems", "House Maintenance", "House, Cars, & Insurance", False, False),
    ("Hygiene", "Health", "Health & Fitness", False, True),
    ("Income Taxes", "Career Income", "Income", False, True),
    ("Internet", "Utilities", "House, Cars, & Insurance", False, True),
    ("Interview Costs", "Tarren's Career Expenses", "Career Expenses", True, False),
    ("January 2024 Vegas Trip", "Trips with Friends", "Vacations & Special Experiences", True, False),
    ("Jonas Brothers Concert", "Trips with Friends", "Vacations & Special Experiences", True, False),
    ("Jules Birthday", "Trips with Friends", "Vacations & Special Experiences", False, True),
    ("Kid's 529", "Financial Investment", "Kid's Enrichment", False, True),
    ("Kid's Birthdays", "Parties", "Vacations & Special Experiences", False, True),
    ("Kid's Clothes", "Kid's Essentials", "Taking Care of the Kids", False, True),
    ("Kid's Sports", "Activities for the Kids", "Kid's Enrichment", True, True),
    ("Kid's Toys", "Activities for the Kids", "Routine Entertainment", True, True),
    ("Kids Photography", "Photos & Memories", "Shopping", True, True),
    ("Kitchen Supplies", "Household Supplies", "House, Cars, & Insurance", True, True),
    ("KPMG Amex", "Tarren's Career Expenses", "Career Expenses", False, True),
    ("Legoland", "Family Vacations", "Vacations & Special Experiences", True, False),
    ("Lil Wayne Concert", "Dates as a Couple", "Vacations & Special Experiences", True, False),
    ("Mariah Carey Vegas Trip", "Trips with Friends", "Vacations & Special Experiences", True, False),
    ("Massages", "Pleasure", "Vanity & Pleasure", True, True),
    ("Meal Kit", "Food for Home", "Food", True, True),
    ("Medication", "Health", "Health & Fitness", False, True),
    ("Mexico Vacation", "Family Vacations", "Vacations & Special Experiences", True, False),
    ("Miscellaneous Shopping", "General Shopping", "Shopping", True, True),
    ("Model 3 Accident", "Tickets & Accidents", "House, Cars, & Insurance", False, False),
    ("Model 3 Payment", "Cars & Transportation", "House, Cars, & Insurance", False, True),
    ("Model X Payment", "Cars & Transportation", "House, Cars, & Insurance", False, True),
    ("Mommy Makeover", "Aesthetics", "Vanity & Pleasure", True, False),
    ("Monterey", "Family Vacations", "Vacations & Special Experiences", True, False),
    ("Motorcross", "Trips with Friends", "Vacations & Special Experiences", True, False),
    ("Movies", "TV, Movies & Music", "Routine Entertainment", True, True),
    ("Museums, Parks & Zoos", "Activities for the Kids", "Routine Entertainment", True, True),
    ("Music", "TV, Movies & Music", "Routine Entertainment", True, True),
    ("Napa Girls Trip", "Trips with Friends", "Vacations & Special Experiences", False, True),
    ("Online Membership", "Utilities", "House, Cars, & Insurance", False, True),
    ("Overdraft Protection", "Financial Fees", "Financial Transactions", False, True),
    ("Palo Alto Trip", "Trips with Friends", "Vacations & Special Experiences", True, False),
    ("Parking", "Cars & Transportation", "House, Cars, & Insurance", False, True),
    ("Parking/Driving Ticket", "Tickets & Accidents", "House, Cars, & Insurance", False, True),
    ("Party Supplies", "Parties", "Vacations & Special Experiences", True, True),
    ("Password Management", "Utilities", "House, Cars, & Insurance", False, True),
    ("Pedra Homeowners", "Homeowners Insurance", "House, Cars, & Insurance", False, True),
    ("Pedra Mortgage", "Mortgages and Rent", "House, Cars, & Insurance", False, True),
    ("Pedra Property Tax", "Mortgages and Rent", "House, Cars, & Insurance", False, True),
    ("Pedra Rent", "Mortgages and Rent", "House, Cars, & Insurance", False, True),
    ("Pedra Trash", "Utilities", "House, Cars, & Insurance", False, True),
    ("Pedra Water Bill", "Utilities", "House, Cars, & Insurance", False, True),
    ("Peloton", "Fitness", "Health & Fitness", True, True),
    ("Pest Control", "House Maintenance", "House, Cars, & Insurance", False, True),
    ("Philly Superbowl Parade", "Dates as a Couple", "Vacations & Special Experiences", True, False),
    ("Phone Bill", "Utilities", "House, Cars, & Insurance", False, True),
    ("Pismo Vacation", "Family Vacations", "Vacations & Special Experiences", True, False),
    ("Pool Care", "House Maintenance", "House, Cars, & Insurance", False, True),
    ("Quad Bike", "Family Vacations", "Vacations & Special Experiences", True, False),
    ("Real Estate Course", "Tarren's Career Expenses", "Career Expenses", True, False),
    ("Red Hawk Trip", "Trips with Friends", "Vacations & Special Experiences", False, True),
    ("Reimbursable Cost", "Reimbursements", "Career Expenses", False, True),
    ("Reimbursement", "Reimbursements", "Career Expenses", False, True),
    ("Reno", "Family Vacations", "Vacations & Special Experiences", True, False),
    ("Reno Football Trip", "Trips with Friends", "Vacations & Special Experiences", True, False),
    ("Restaurants", "Eating Out", "Food", True, True),
    ("Ridgeview Gas & Electricity", "Utilities", "House, Cars, & Insurance", False, True),
    ("Ridgeview Homeowners", "Homeowners Insurance", "House, Cars, & Insurance", False, True),
    ("Ridgeview Mortgage", "Mortgages and Rent", "House, Cars, & Insurance", False, True),
    ("Ridgeview Trash", "Utilities", "House, Cars, & Insurance", False, True),
    ("Sam's Birthday Weekend", "Trips with Friends", "Vacations & Special Experiences", True, False),
    ("San Sebastian Vacation", "Trips with Friends", "Vacations & Special Experiences", True, False),
    ("Sand Mountain", "Family Vacations", "Vacations & Special Experiences", True, False),
    ("Santa Cruz", "Family Vacations", "Vacations & Special Experiences", True, False),
    ("Security", "Utilities", "House, Cars, & Insurance", False, True),
    ("Silva Valley PTA", "Donations", "Donations & Giving", True, False),
    ("Six Flags", "Family Vacations", "Vacations & Special Experiences", True, False),
    ("Sleep Aid", "Health", "Health & Fitness", False, True),
    ("Streaming Services", "TV, Movies & Music", "Routine Entertainment", True, True),
    ("Sundries", "Health", "Health & Fitness", False, True),
    ("Tahoe", "Family Vacations", "Vacations & Special Experiences", True, False),
    ("Target", "Food for Home", "Food", False, True),
    ("Tarren's Birthday in Vegas", "Trips with Friends", "Vacations & Special Experiences", True, False),
    ("Tarren's Payroll", "Career Income", "Income", False, True),
    ("Tax Return", "Career Income", "Income", False, True),
    ("Teresa", "Childcare/Tutoring", "Taking Care of the Kids", True, False),
    ("Tesla Charger Installation", "Cars & Transportation", "House, Cars, & Insurance", True, False),
    ("THC", "Altered States", "Vanity & Pleasure", True, True),
    ("Tim's Vegas Trip", "Dates as a Couple", "Vacations & Special Experiences", True, False),
    ("Tolls", "Cars & Transportation", "House, Cars, & Insurance", False, True),
    ("Tools, Lawn & Garden Supplies", "House Maintenance", "House, Cars, & Insurance", False, True),
    ("Trampoline Park", "Parks, Zoos & Museums", "Routine Entertainment", True, True),
    ("Transfer Payment", "Financial Transfers", "Financial Transactions", False, True),
    ("Tutoring", "Childcare/Tutoring", "Kid's Enrichment", True, True),
    ("Typing Course", "David's Career Expenses", "Career Expenses", True, False),
    ("Verily Meals", "Eating Out", "Career Expenses", True, True),
    ("Volvo Payment", "Cars & Transportation", "House, Cars, & Insurance", False, True),
    ("Watching Football", "TV, Movies & Music", "Routine Entertainment", True, True),
    ("Water Bill", "Utilities", "House, Cars, & Insurance", False, True),
    ("Website Domains", "Aesthetics", "Vanity & Pleasure", True, True),
    ("Zach", "Childcare/Tutoring", "Taking Care of the Kids", False, True),
]


def seed_budget_categories(db):
    """Seed budget categories if table is empty."""
    from .models import BudgetCategory
    if db.query(BudgetCategory).count() > 0:
        return
    db.add_all([
        BudgetCategory(
            sub_category=sub, category=cat, macro_category=macro,
            is_discretionary=disc, is_recurring=rec
        )
        for sub, cat, macro, disc, rec in BUDGET_CATEGORIES
    ])
    db.commit()
